version: "3"
services:
  app:
    container_name: template_prod_app
    build:
      context: .
      dockerfile: docker/app/prod/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
  api:
    container_name: template_prod_api
    build:
      context: .
      dockerfile: docker/api/prod/Dockerfile
    ports:
      - 4000:4000
  db:
    image: mysql
    container_name: template_dev_db
    env_file: ./docker/db/db.env
    restart: always
    expose:
      - 3306
    volumes:
      - ./docker/db/data:/var/lib/mysql